### PR TITLE
Support for the new 1.20 sign structure

### LINKED ISSUE #19: Marker fails for MC 1.20
The tool mapcrafter_markes fails for Minecraft 1.20 with the following error:

`terminate called after throwing an instance of 'mapcrafter::mc::nbt::TagNotFound'
  what():  Unable to find (const) tag 'Text1'
`

### PR DESCRIPTION
**Pull request by doismellburning**
Fixes #19

### CODE REVIEW

**Comment by doismellburning** [comment]
I'm still sorting out a test for this, but it builds cleanly and _looks_ right...

**Comment by doismellburning** [comment]
Confirmed in local runs on a 1.20 world, but I think it will be some time before I figure out how to write a good test for this, sorry

**Comment by miclav** [comment]
Thanks for looking into this issue. 👍

**Comment by doismellburning** [comment]
Thanks for all your work on Mapcrafter!

**Comment by doismellburning** [comment]
Anything I can do to help get an official Docker build out, or all good? Cheers :)

**Pull request merged**
